# Generated by Django 5.1.1 on 2024-09-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_cliente_ciudad_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
