# Generated by Django 5.1.1 on 2024-10-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_producto_color_remove_producto_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(choices=[('4 Tonillos', '4 Tornillos'), ('Clasico', 'Clásico'), ('Charol', 'Charol')], max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Tejido', 'Tejido'), ('Rejo', 'Rejo'), ('Plano', 'Plano'), ('Sencillo', 'Sencillo')], max_length=255),
        ),
    ]
