# Generated by Django 5.1.1 on 2024-10-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_producto_modelo_alter_producto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Tejido', 'tejido'), ('Rejo', 'rejo'), ('Plano', 'plano'), ('Sencillo', 'sencillo')], max_length=255),
        ),
    ]
