# Generated by Django 5.1.1 on 2024-10-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_producto_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='colorSecundario',
            new_name='colorTejido',
        ),
        migrations.AlterField(
            model_name='producto',
            name='colorPrincipal',
            field=models.CharField(choices=[('Negro', 'negro'), ('Roble', 'roble'), ('Crudo', 'crudo'), ('Chocolate', 'chocolate'), ('Envejecido', 'envejecido')], max_length=255),
        ),
    ]
