# Generated by Django 5.1.1 on 2024-10-19 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_colorsecundario_producto_colortejido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadproducto',
            name='fechaCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
