# Generated by Django 5.1.1 on 2025-06-05 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_detalleventa_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='subtotal',
        ),
    ]
