# Generated by Django 5.1.1 on 2025-06-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_detalleventa_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadproducto',
            name='contador',
            field=models.IntegerField(default=0),
        ),
    ]
