# Generated by Django 5.1.1 on 2025-06-27 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_unidadproducto_contador'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadproducto',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ventas'),
        ),
    ]
