# Generated by Django 5.1.1 on 2025-06-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_unidadproducto_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorUnidadProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador', models.IntegerField(default=0)),
            ],
        ),
    ]
