# Generated by Django 5.1.1 on 2025-06-28 21:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_contadorunidadproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contadorunidadproducto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
