# Generated by Django 5.1.1 on 2025-06-28 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_contadorunidadproducto_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadproducto',
            name='contador',
        ),
    ]
