# Generated by Django 5.2.6 on 2026-01-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_unidadproducto_contador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadproducto',
            name='numeroSerie',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
