# Generated by Django 5.2.6 on 2026-01-20 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_unidadproducto_numeroserie'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.unidadproducto'),
        ),
    ]
