# Generated by Django 5.2.6 on 2026-03-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_grupoimagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='colorCordon1',
            field=models.CharField(blank=True, choices=[('Naranja', 'Naranja'), ('Negro', 'Negro'), ('Roble', 'Roble'), ('Crudo', 'Crudo'), ('Azul Celeste', 'Azul Celeste'), ('Azul Rey', 'Azul Rey'), ('Amarillo', 'Amarillo'), ('Rojo', 'Rojo'), ('Rosado', 'Rosado'), ('Verde Claro', 'Verde Claro'), ('Verde Militar', 'Verde Militar'), ('Crudo Amarillo', 'Crudo Amarillo'), ('Blanco Natural', 'Blanco Natural')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='colorCordon2',
            field=models.CharField(blank=True, choices=[('Naranja', 'Naranja'), ('Negro', 'Negro'), ('Roble', 'Roble'), ('Crudo', 'Crudo'), ('Azul Celeste', 'Azul Celeste'), ('Azul Rey', 'Azul Rey'), ('Amarillo', 'Amarillo'), ('Rojo', 'Rojo'), ('Rosado', 'Rosado'), ('Verde Claro', 'Verde Claro'), ('Verde Militar', 'Verde Militar'), ('Crudo Amarillo', 'Crudo Amarillo'), ('Blanco Natural', 'Blanco Natural')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='colorCoronas',
            field=models.CharField(blank=True, choices=[('Naranja', 'Naranja'), ('Negro', 'Negro'), ('Roble', 'Roble'), ('Crudo', 'Crudo'), ('Azul Celeste', 'Azul Celeste'), ('Azul Rey', 'Azul Rey'), ('Amarillo', 'Amarillo'), ('Rojo', 'Rojo'), ('Rosado', 'Rosado'), ('Verde Claro', 'Verde Claro'), ('Verde Militar', 'Verde Militar'), ('Crudo Amarillo', 'Crudo Amarillo'), ('Blanco Natural', 'Blanco Natural')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='colorManzanos',
            field=models.CharField(blank=True, choices=[('Naranja', 'Naranja'), ('Negro', 'Negro'), ('Roble', 'Roble'), ('Crudo', 'Crudo'), ('Azul Celeste', 'Azul Celeste'), ('Azul Rey', 'Azul Rey'), ('Amarillo', 'Amarillo'), ('Rojo', 'Rojo'), ('Rosado', 'Rosado'), ('Verde Claro', 'Verde Claro'), ('Verde Militar', 'Verde Militar'), ('Crudo Amarillo', 'Crudo Amarillo'), ('Blanco Natural', 'Blanco Natural')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='colorSogaRienda',
            field=models.CharField(blank=True, choices=[('Naranja', 'Naranja'), ('Negro', 'Negro'), ('Roble', 'Roble'), ('Crudo', 'Crudo'), ('Azul Celeste', 'Azul Celeste'), ('Azul Rey', 'Azul Rey'), ('Amarillo', 'Amarillo'), ('Rojo', 'Rojo'), ('Rosado', 'Rosado'), ('Verde Claro', 'Verde Claro'), ('Verde Militar', 'Verde Militar'), ('Crudo Amarillo', 'Crudo Amarillo'), ('Blanco Natural', 'Blanco Natural')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='colorPrincipal',
            field=models.CharField(choices=[('Negro', 'Negro'), ('Roble', 'Roble'), ('Crudo', 'Crudo'), ('Chocolate', 'Chocolate'), ('Envejecido', 'Envejecido')], max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='colorTejido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(choices=[('4 Tornillos', '4 Tornillos'), ('Clasico', 'Clásico'), ('Charol', 'Charol')], max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Tejido', 'Tejido'), ('Rejo', 'Rejo'), ('Plano', 'Plano'), ('Sencillo', 'Sencillo')], max_length=255),
        ),
    ]
