# Generated by Django 5.2.1 on 2026-05-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_producto_colorcordon1_producto_colorcordon2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
