# Generated by Django 5.2.1 on 2026-05-15 18:50

from django.db import migrations, models

COLORES_INICIALES = [
    'Naranja', 'Negro', 'Roble', 'Crudo', 'Azul Celeste', 'Azul Rey',
    'Amarillo', 'Rojo', 'Rosado', 'Verde Claro', 'Verde Militar',
    'Crudo Amarillo', 'Blanco Natural', 'Chocolate', 'Envejecido',
]

def cargar_colores(apps, schema_editor):
    Color = apps.get_model('api', 'Color')
    for nombre in COLORES_INICIALES:
        Color.objects.get_or_create(nombre=nombre)

def descargar_colores(apps, schema_editor):
    Color = apps.get_model('api', 'Color')
    Color.objects.filter(nombre__in=COLORES_INICIALES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_cliente_identificacion_opcional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RunPython(cargar_colores, descargar_colores),
        migrations.AlterField(
            model_name='producto',
            name='colorCordon1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='colorCordon2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='colorCoronas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='colorManzanos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='colorPrincipal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='colorSogaRienda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
